/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "google-otpauth-migration.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MigrationPayload, MigrationPayload, AUTO)


PB_BIND(MigrationPayload_OtpParameters, MigrationPayload_OtpParameters, AUTO)









