FROM blockstream/verde@sha256:3338e3fc877261df4017ddc8fdb173e43e26922a3551f8d2000e0935e4d250de

RUN echo "source /root/esp/esp-idf/export.sh" >> /etc/bash.bashrc

COPY .git /host/jade/.git
RUN git clone /host/jade/ /jade
WORKDIR /jade
RUN git submodule init
RUN git submodule update
