services:
  dev:
    image: blockstream/jade_builder@sha256:8b739db85b6b99664db0e3ece57cddfa4e0fee4101a20ca930c391273f21e2f9
    volumes:
      - .:/host/jade/
      - /dev/serial/by-id:/dev/serial/by-id
    working_dir: /host/jade/
    privileged: true
    tty: true
