services:
  dev:
    image: blockstream/jade_builder@sha256:9f98cf9a03b6b98fcdf70cf84569304e85842452f2a3bdc5de7d8128da208013
    volumes:
      - .:/host/jade/
      - /dev/serial/by-id:/dev/serial/by-id
    working_dir: /host/jade/
    privileged: true
    tty: true
