FROM blockstream/verde@sha256:bb20e230564195a3a9f8b4dfa338af15da8c06862ecd487cf3b7e09279435055

RUN echo "source /root/esp/esp-idf/export.sh" >> /etc/bash.bashrc

COPY .git /host/jade/.git
RUN git clone /host/jade/ /jade
WORKDIR /jade
RUN git submodule update --init --recursive
