FROM blockstream/verde@sha256:391a4337c174f2eb47dc9f31d7e25d19a5f101bbc07fa8a296866c1ee52b8473 as builder

ARG SDK_CONFIG=configs/sdkconfig_qemu_psram.defaults

WORKDIR /jade

COPY . .
RUN cp ${SDK_CONFIG} sdkconfig.defaults
RUN . /root/esp/esp-idf/export.sh && idf.py all
RUN ./tools/fwprep.py build/jade.bin build

ENV PATH=$PATH:/jade/main/qemu
RUN make-flash-img.sh

FROM debian:bookworm@sha256:321341744acb788e251ebd374aecc1a42d60ce65da7bd4ee9207ff6be6686a62

RUN apt-get update -yqq && apt-get install -yqq libpixman-1-dev libglib2.0-dev libslirp-dev libncurses-dev

COPY --from=builder /flash_image.bin /flash_image.bin
COPY --from=builder /qemu_efuse.bin /qemu_efuse.bin

COPY --from=builder /opt/bin/qemu-system-xtensa /opt/bin/qemu-system-xtensa
COPY --from=builder /opt/share/qemu /opt/share/qemu
COPY --from=builder /jade/main/qemu/ /jade/main/qemu/

ENV PATH=$PATH:/jade/main/qemu

CMD [ "qemu_run.sh" ]
