FROM blockstream/jade_builder@sha256:cbf0aabee7513dc8cad8f1d69a5e00f5b73bcd0965a44254627c0de4bfc8c4f2

ARG QEMU_CONFIG_ARGS="--dev --ci --psram"
ARG QEMU_GDB=""

WORKDIR /jade

COPY . .
RUN ./tools/switch_to.sh qemu ${QEMU_CONFIG_ARGS}
RUN cd /opt/esp/idf && . ./export.sh && cd /jade && idf.py all && ./tools/fwprep.py build/jade.bin build && ./main/qemu/make_flash_img.sh
CMD ["sh", "-c", "exec /jade/main/qemu/qemu_run.sh ${QEMU_GDB}"]
