services:
  dev:
    image: blockstream/jade_builder@sha256:5db8e13ca640e6b969d66139d708610c27d39a1c4d78ca096ee98f2b4c89130f
    volumes:
      - .:/host/jade/
      - /dev/serial/by-id:/dev/serial/by-id
    working_dir: /host/jade/
    privileged: true
    tty: true
