#ifndef BUTTON_EVENTS_H_
#define BUTTON_EVENTS_H_

typedef enum {
    BTN_EXIT_MESSAGE_SCREEN,

    BTN_YES,
    BTN_NO,

    BTN_TX_SCREEN_NEXT,
    BTN_TX_SCREEN_PREV,
    BTN_TX_SCREEN_EXIT,

    BTN_CANCEL_SIGNATURE,
    BTN_ACCEPT_SIGNATURE,

    BTN_CANCEL_ADDRESS,
    BTN_ACCEPT_ADDRESS,

    BTN_CANCEL_OTA,
    BTN_ACCEPT_OTA,

    BTN_REBOOT,

    BTN_BLE_CONFIRM,
    BTN_BLE_DENY,

    BTN_NEW_MNEMONIC,

    BTN_NEW_MNEMONIC_12_BEGIN,
    BTN_NEW_MNEMONIC_24_BEGIN,

    BTN_MNEMONIC_PREV,
    BTN_MNEMONIC_NEXT,
    BTN_MNEMONIC_EXIT,
    BTN_MNEMONIC_VERIFY,

    BTN_RECOVER_MNEMONIC,

    BTN_RECOVER_MNEMONIC_12_BEGIN,
    BTN_RECOVER_MNEMONIC_24_BEGIN,

    BTN_QR_MNEMONIC_BEGIN,
    BTN_QR_MNEMONIC_SCAN,
    BTN_QR_MNEMONIC_EXIT,

    BTN_KEYBOARD_BACKSPACE,
    BTN_KEYBOARD_ENTER,
    BTN_KEYBOARD_A,
    BTN_KEYBOARD_B,
    BTN_KEYBOARD_C,
    BTN_KEYBOARD_D,
    BTN_KEYBOARD_E,
    BTN_KEYBOARD_F,
    BTN_KEYBOARD_G,
    BTN_KEYBOARD_H,
    BTN_KEYBOARD_I,
    BTN_KEYBOARD_J,
    BTN_KEYBOARD_K,
    BTN_KEYBOARD_L,
    BTN_KEYBOARD_M,
    BTN_KEYBOARD_N,
    BTN_KEYBOARD_O,
    BTN_KEYBOARD_P,
    BTN_KEYBOARD_Q,
    BTN_KEYBOARD_R,
    BTN_KEYBOARD_S,
    BTN_KEYBOARD_T,
    BTN_KEYBOARD_U,
    BTN_KEYBOARD_V,
    BTN_KEYBOARD_W,
    BTN_KEYBOARD_X,
    BTN_KEYBOARD_Y,
    BTN_KEYBOARD_Z,

    BTN_INITIALIZE,
    BTN_SLEEP,
    BTN_SETTINGS,
    BTN_BLE,
    BTN_INFO,

    BTN_CONNECT_BACK,
    BTN_CONNECT_USB,
    BTN_CONNECT_BLE,

    BTN_SETTINGS_TOGGLE_ORIENTATION,
    BTN_SETTINGS_TIMEOUT_0,
    BTN_SETTINGS_TIMEOUT_1,
    BTN_SETTINGS_TIMEOUT_2,
    BTN_SETTINGS_TIMEOUT_3,
    BTN_SETTINGS_TIMEOUT_4,
    BTN_SETTINGS_TIMEOUT_5,
    BTN_SETTINGS_EMERGENCY_RESTORE,
    BTN_SETTINGS_LEGAL,
    BTN_SETTINGS_RESET,
    BTN_SETTINGS_EXIT,

    BTN_BLE_TOGGLE_ENABLE,
    BTN_BLE_RESET_PAIRING,

    BTN_INFO_SHOW_XPUB,
    BTN_INFO_LEGAL,
    BTN_INFO_EXIT,

    BTN_LEGAL_NEXT,
    BTN_LEGAL_PREV,

    BTN_BLE_EXIT,

    BTN_PINSERVER_DETAILS_CONFIRM,
    BTN_PINSERVER_DETAILS_DENY,

} button_event_id;

#endif /* BUTTON_EVENTS_H_ */
